image: gradle:6.7-jdk11

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-menu-microservice:
  stage: build
  script:
    gradle menu-microservice:assemble menu-microservice:testClasses

checkStyle-menu-microservice:
  stage: staticAnalysis
  script:
    gradle menu-microservice:checkstyleMain menu-microservice:checkStyleTest


PMD-menu-microservice:
  stage: staticAnalysis
  script:
    gradle menu-microservice:pmdMain

test-menu-microservice:
  stage: test
  script:
    - gradle menu-microservice:test menu-microservice:jacocoTestReport
    - cat menu-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
